name: Multi-job e dependência

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Etapa de build
        run: echo "Construindo projeto..."

  deploy:
    needs: build  # Faz o deploy depender do build
    runs-on: ubuntu-latest
    steps:
      - name: Etapa de deploy
        run: echo "Deploy concluído!"
       
